require:
  - rubocop-rspec
  # - rubocop-jekyll

AllCops:
  Exclude:
    - demo/_site/**/*
    - exe/**/*
    - vendor/**/*
    - Gemfile*
  NewCops: enable
  TargetRubyVersion: 2.6

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - jekyll_plugin_support.gemspec

Metrics/MethodLength:
  Max: 25

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
