AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
