author: Mike Slinn
collections:
  stuff:
    output: true
    relative_directory: _stuff
    sort_by: order
collections_dir: collections
compress_html:
  blanklines: false
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  profile: false
  startings: [html, head, body]
domain: mslinn.com
email: bogus@example.com
exclude:  # Wildcards are not supported yet https://github.com/jekyll/jekyll-watch/pull/93
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - .ruby-version
  - .vscode
  - BingSiteAuth.xml
  - Gemfile
  - Gemfile.lock
  - README.md
  - /assets/images/qrcodes/
demo_block_tag:
  die_on_demo_block_error: false
  die_on_standard_error: false
demo_inline_tag:
  die_on_demo_tag_error: false
  die_on_standard_error: false
ignore_theme_config: true
jekyll_plugin_support:
  pry_on_standard_error: false
liquid:
  error_mode: strict
  # strict_filters: true
  # strict_variables: true
liquid_vars:
  development:
    var1: 'http://localhost:4444/demo_block_tag.html'
    var2: 'http://localhost:4444/demo_inline_tag.html'
  production:
    var1: 'https://github.com/django/django/blob/3.1.7'
    var2: 'https://github.com/django-oscar/django-oscar/blob/3.0.2'
  var3: 'Assigned in _config.yml'
plugin_loggers:
  PluginMetaLogger: info
  CleanHook: warn
  DocumentHooks: warn
  DraftFilter: debug
  QRCodeGenerator: debug
  MyBlock: warn
  PageHooks: warn
  PostHooks: warn
  SiteHooks: warn
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugins: # Use file name of the plugin entry point, not the gem name
  - jekyll_plugin_logger
  # - html-proofer
  - jekyll
qrcode:
  bg_color: '#666'
  fg_color: black
sass:
  style: compressed
title: Jekyll Plugin Support Demo
url: https://bogus.jekylldemo.com
