author: Mike Slinn
compress_html:
  blanklines: false
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  profile: false
  startings: [html, head, body]
domain: bogus.jekylldemo.com
email: bogus@jekylldemo.com
exclude:  # Wildcards are not supported yet https://github.com/jekyll/jekyll-watch/pull/93
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - .ruby-version
  - .vscode
  - BingSiteAuth.xml
  - Gemfile
  - Gemfile.lock
  - README.md
demo_block_tag:
  die_on_custom_error: false
  die_on_standard_error: false
demo_inline_tag:
  die_on_custom_error: false
  die_on_standard_error: false
ignore_theme_config: true
liquid:
  error_mode: strict
  # strict_filters: true
  # strict_variables: true
plugin_loggers:
  PluginMetaLogger: info
  CleanHook: warn
  DocumentHooks: warn
  DraftFilter: debug
  MyBlock: warn
  PageHooks: warn
  PostHooks: warn
  SiteHooks: warn
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugins: # Use file name of the plugin entry point, not the gem name
  - jekyll_plugin_logger
  # - html-proofer
  - jekyll
plugin-vars:
  development:
    var1: 'http://localhost:4444/demo_block_tag.html'
    var2: 'http://localhost:4444/demo_inline_tag.html'
  production:
    var1: 'https://github.com/django/django/blob/3.1.7'
    var2: 'https://github.com/django-oscar/django-oscar/blob/3.0.2'
  var3: 'https://github.com/mslinn'
sass:
  style: compressed
title: Jekyll Plugin Support Demo
url: https://bogus.jekylldemo.com
