author: Mike Slinn
compress_html:
  blanklines: false
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  profile: false
  startings: [html, head, body]
domain: bogus.jekylldemo.com
email: bogus@jekylldemo.com
exclude:  # Wildcards are not supported yet https://github.com/jekyll/jekyll-watch/pull/93
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - .ruby-version
  - .vscode
  - BingSiteAuth.xml
  - Gemfile
  - Gemfile.lock
  - README.md
ignore_theme_config: true
liquid:
  error_mode: strict
  # strict_filters: true
  # strict_variables: true
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugin_loggers:
  PluginMetaLogger: info
  CleanHook: warn
  DocumentHooks: warn
  DraftFilter: debug
  MyBlock: warn
  PageHooks: warn
  PostHooks: warn
  SiteHooks: warn
plugin_suppport:
  enable_stack_dump: true
plugins: # Use file name of the plugin entry point, not the gem name
  - jekyll_plugin_logger
  - html-proofer
  - jekyll
sass:
  style: compressed
title: Jekyll Plugin Support Demo
url: https://bogus.jekylldemo.com
