source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.3'

group :jekyll_plugins do
  gem 'jekyll_all_collections'
  gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets'
  gem 'jekyll_badge', '>= 0.1.2'
  gem 'jekyll_draft', '>= 2.0.2'
  gem 'jekyll_emoji_tag'
  gem 'jekyll-environment-variables'
  gem 'jekyll_flexible_include'
  gem 'jekyll_google_translate'
  gem 'jekyll_href', '>= 1.2.10'
  gem 'jekyll_img'
  gem 'jekyll_outline'
  gem 'jekyll_plugin_support', path: '../'
  gem 'jekyll_pre'
  gem 'jekyll_qr_generator'
  gem 'jekyll_quote'
  gem 'jekyll_reading_time'
  gem 'jekyll_run'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
end
