source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.2'

group :jekyll_plugins do
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll_draft'
  gem 'jekyll-environment-variables'
  gem 'jekyll_plugin_support', path: '../'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
end

gem 'debase', '0.2.5.beta2', require: false
gem 'rake', require: false
gem 'ruby-debug-ide', require: false
